### ISSUE TITLE
React architecture - functional vs class decision

### ISSUE THREAD

**Issue by that-coder** [neoito-hub/neo-chat#1]

**Comment by DudeLogic** [comment]
I am preferring Functional architecture. It's easy to split up components and code feels more compact

**Comment by sajanthomas01** [comment]
functional

**Comment by muhammadthahir6** [comment]
For an app of this scale, functional component is more suitable

**Comment by muhammadthahir6** [comment]
> I am preferring Functional architecture. It's easy to split up components and code feels more compact

advantage of performance improvement too

**Comment by thealpha93** [comment]
I also feel like functional is more apt

**Comment by that-coder** [comment]
Cool. let's build with functional.
